export { Hero } from './Hero'
export { Services } from './Services'
export { Process } from './Process'
export { About } from './About'
export { Testimonials } from './Testimonials'
export { Contact } from './Contact'
